### ISSUE TITLE
Controller models not visible

### ISSUE THREAD

**Issue by knochenhans** [NeoSpark314/godot_oculus_quest_toolkit#74] opened 2021-11-26 22:36 UTC
Hi, I recently came back to playing around with the Godot Oculus Quest Toolkit. On my Quest 1, using Godot 3.4 and Quest Toolkit 0.4.2 (also tried the current git version), neither the demo scenes nor my own scenes show the controller models. They are visible in Godot’s desktop preview, but not on the actual Quest. I see no error messages in the debug log and the controllers themselves and tracking works fine, just the models are invisible. I also tried explicitly setting the controller models type to “Quest 1” in the controller nodes. I also tried GLES 2 as well as 3.

**Comment by NeoSpark314** [comment] 2021-11-29 06:54
The problem is related to godot 3.4; the included export template of the toolkit is not yet updated to godot 3.4 and probably something in the mesh conversion (in the .import folder) changed. With godot 3.3 it should work;

**Comment by knochenhans** [comment] 2021-11-29 16:24
Thanks, I can confirm the models are visible again when exporting the project in a pre-3.4 version of Godot (had to reimport the models though to make it work).

**Comment by nightblade9** [comment] 2022-01-25 01:46
Hi,

It looks like this issue is still present. Is there a rough timeline for a fix?

**Comment by NeoSpark314** [comment] 2022-06-20 17:06
Fixed with 28b994eb4f3c2c47a3fe1cc76ce9e2ea78503769 (updated included godot binaries to current godot version)

**Closed as completed by NeoSpark314** 2022-06-20 17:06 UTC
